use std::ffi::OsString;
use std::os::windows::ffi::{OsStrExt, OsStringExt};
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::atomic_file;

use super::storage::{ensure_directory_chain, read_replaceable_bounded, regular_file_or_missing};

const MAX_ENVIRONMENT_SCRIPT_BYTES: u64 = 1024 * 1024;

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EnvironmentPlan {
    variables: Vec<(String, Option<String>)>,
    paths: Vec<PathBuf>,
}

impl EnvironmentPlan {
    pub fn set(&mut self, name: &str, value: Option<impl Into<String>>) -> Result<(), String> {
        if !valid_name(name) {
            return Err(format!(
                "invalid generated environment variable name: {name}"
            ));
        }
        if self
            .variables
            .iter()
            .any(|(existing, _)| existing.eq_ignore_ascii_case(name))
        {
            return Err(format!(
                "generated environment variable is already defined: {name}"
            ));
        }
        self.variables
            .push((name.to_owned(), value.map(Into::into)));
        Ok(())
    }

    pub fn prepend_path(&mut self, path: impl Into<PathBuf>) -> Result<(), String> {
        let path = absolute_normalized(path.into())?;
        if !self
            .paths
            .iter()
            .any(|existing| paths_equal(existing, &path))
        {
            self.paths.push(path);
        }
        Ok(())
    }

    pub(crate) fn variables(&self) -> &[(String, Option<String>)] {
        &self.variables
    }

    pub(crate) fn paths(&self) -> &[PathBuf] {
        &self.paths
    }

    pub fn render(&self) -> EnvironmentScripts {
        let mut cmd = String::from(
            "@echo off\r\nrem Generated by Swaw Kit Proj. Regenerate it; do not edit.\r\n",
        );
        let mut ps1 = String::from("# Generated by Swaw Kit Proj. Regenerate it; do not edit.\r\n");
        for (name, value) in &self.variables {
            match value {
                Some(value) => {
                    cmd.push_str(&format!("set \"{name}={}\"\r\n", value.replace('%', "%%")));
                    ps1.push_str(&format!(
                        "$env:{name} = '{}'\r\n",
                        value.replace('\'', "''")
                    ));
                }
                None => {
                    cmd.push_str(&format!("set \"{name}=\"\r\n"));
                    ps1.push_str(&format!(
                        "Remove-Item -LiteralPath 'Env:{name}' -ErrorAction SilentlyContinue\r\n"
                    ));
                }
            }
        }
        if !self.paths.is_empty() {
            let prefix = self
                .paths
                .iter()
                .map(|path| path.to_string_lossy())
                .collect::<Vec<_>>()
                .join(";");
            cmd.push_str(&format!(
                "set \"PATH={};%PATH%\"\r\n",
                prefix.replace('%', "%%")
            ));
            ps1.push_str(&format!(
                "$env:PATH = '{};' + $env:PATH\r\n",
                prefix.replace('\'', "''")
            ));
        }
        let digest = format!(
            "{:x}",
            Sha256::digest(format!("{cmd}\n---\n{ps1}").as_bytes())
        );
        let revision = digest[..16].to_owned();
        EnvironmentScripts { revision, cmd, ps1 }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EnvironmentScripts {
    revision: String,
    cmd: String,
    ps1: String,
}

impl EnvironmentScripts {
    pub fn revision(&self) -> &str {
        &self.revision
    }

    pub fn cmd(&self) -> &str {
        &self.cmd
    }

    pub fn ps1(&self) -> &str {
        &self.ps1
    }

    pub fn publish(&self, data_root: &Path) -> Result<bool, String> {
        let export = ensure_directory_chain(
            data_root,
            &["modules", "kernel", ".dev", "setup", "export"],
            "development environment export",
        )
        .map_err(|error| error.to_string())?;
        let cmd_path = export.join("env.cmd");
        let ps1_path = export.join("env.ps1");
        let cmd_bytes = self.cmd.as_bytes();
        let mut ps1_bytes = vec![0xef, 0xbb, 0xbf];
        ps1_bytes.extend_from_slice(self.ps1.as_bytes());
        if same_file(&cmd_path, cmd_bytes)? && same_file(&ps1_path, &ps1_bytes)? {
            return Ok(false);
        }
        publish_one(&cmd_path, cmd_bytes, "env.cmd")?;
        publish_one(&ps1_path, &ps1_bytes, "env.ps1")?;
        Ok(true)
    }
}

fn same_file(path: &Path, expected: &[u8]) -> Result<bool, String> {
    if !regular_file_or_missing(path, "development environment script")
        .map_err(|error| error.to_string())?
    {
        return Ok(false);
    }
    match read_replaceable_bounded(
        path,
        "development environment script",
        MAX_ENVIRONMENT_SCRIPT_BYTES,
    ) {
        Ok(actual) => Ok(actual == expected),
        Err(error) if error.kind() == std::io::ErrorKind::InvalidData => Ok(false),
        Err(error) => Err(error.to_string()),
    }
}

fn publish_one(path: &Path, content: &[u8], name: &str) -> Result<(), String> {
    atomic_file::publish(path, content).map_err(|error| {
        format!(
            "cannot publish development {name} '{}': {error}",
            path.display()
        )
    })
}

fn valid_name(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes
        .next()
        .is_some_and(|byte| byte.is_ascii_alphabetic() || byte == b'_')
        && bytes.all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}

fn absolute_normalized(path: PathBuf) -> Result<PathBuf, String> {
    if !path.is_absolute() {
        return Err(format!(
            "generated environment PATH must be absolute: {}",
            path.display()
        ));
    }
    let path = std::path::absolute(&path).map_err(|error| {
        format!(
            "cannot resolve generated environment PATH '{}': {error}",
            path.display()
        )
    })?;
    if path.parent().is_none() {
        return Ok(path);
    }
    let mut value = path.as_os_str().encode_wide().collect::<Vec<_>>();
    while value
        .last()
        .is_some_and(|value| *value == b'\\' as u16 || *value == b'/' as u16)
    {
        value.pop();
    }
    Ok(PathBuf::from(OsString::from_wide(&value)))
}

fn paths_equal(left: &Path, right: &Path) -> bool {
    left.to_string_lossy()
        .eq_ignore_ascii_case(&right.to_string_lossy())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT: AtomicU64 = AtomicU64::new(0);

    #[test]
    fn rendering_is_ordered_escaped_and_power_shell_compatible() {
        let mut plan = EnvironmentPlan::default();
        plan.set("B_VALUE", Some("50% 'ready'")).unwrap();
        plan.set("A_REMOVE", None::<String>).unwrap();
        plan.prepend_path(PathBuf::from(r"C:\Tools\A")).unwrap();
        plan.prepend_path(PathBuf::from(r"c:\tools\a")).unwrap();
        let scripts = plan.render();

        assert!(scripts.cmd().find("B_VALUE").unwrap() < scripts.cmd().find("A_REMOVE").unwrap());
        assert!(scripts.cmd().contains("set \"A_REMOVE=\"\r\n"));
        assert!(scripts.cmd().contains("set \"B_VALUE=50%% 'ready'\"\r\n"));
        assert!(scripts.ps1().contains("$env:B_VALUE = '50% ''ready'''"));
        assert_eq!(scripts.cmd().matches(";%PATH%").count(), 1);
        assert_eq!(scripts.revision(), "800c00d66454dce0");
    }

    #[test]
    fn publication_is_byte_stable_and_uses_the_required_encodings() {
        let data_root = std::env::temp_dir().join(format!(
            "swawkit-setup-environment-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&data_root).unwrap();
        let mut plan = EnvironmentPlan::default();
        plan.set("B_VALUE", Some("one")).unwrap();
        plan.set("A_VALUE", Some("two")).unwrap();
        let scripts = plan.render();

        assert!(scripts.publish(&data_root).unwrap());
        assert!(!scripts.publish(&data_root).unwrap());
        let export = data_root.join("modules/kernel/.dev/setup/export");
        assert_eq!(
            fs::read(export.join("env.cmd")).unwrap(),
            scripts.cmd().as_bytes()
        );
        let ps1 = fs::read(export.join("env.ps1")).unwrap();
        assert_eq!(&ps1[..3], &[0xef, 0xbb, 0xbf]);
        assert_eq!(&ps1[3..], scripts.ps1().as_bytes());
        assert!(scripts.cmd().find("B_VALUE").unwrap() < scripts.cmd().find("A_VALUE").unwrap());
        fs::remove_dir_all(data_root).unwrap();
    }
}
