Set-StrictMode -Version 2.0

function New-ProjDevEnvironmentPlan {
    param([Parameter(Mandatory = $true)][object]$Context)

    $Variables = [Collections.Specialized.OrderedDictionary]::new()
    $Variables.Add('SWAWKIT_PROJ_DEV_ENV_SCHEMA', 'swawkit.proj-dev.environment.v0')
    $Variables.Add('SWAWKIT_PROJ_DEV_PROJECT_ROOT', [string]$Context.ProjectRoot)
    $Variables.Add('SWAWKIT_PROJ_DEV_ENV_ROOT', [string]$Context.EnvironmentRoot)
    return [pscustomobject][ordered]@{
        Variables = $Variables
        PathPrefixes = [Collections.Generic.List[string]]::new()
    }
}

function Set-ProjDevEnvironmentVariable {
    param(
        [Parameter(Mandatory = $true)][object]$Plan,
        [Parameter(Mandatory = $true)][string]$Name,
        [AllowNull()][string]$Value
    )

    if ($Name -cnotmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "Invalid generated environment variable name: $Name"
    }
    foreach ($ExistingName in $Plan.Variables.Keys) {
        if ($Name.Equals(
            [string]$ExistingName,
            [StringComparison]::OrdinalIgnoreCase
        )) {
            throw "Generated environment variable is already defined: $Name"
        }
    }
    $Plan.Variables.Add($Name, $Value)
}

function Add-ProjDevEnvironmentPath {
    param(
        [Parameter(Mandatory = $true)][object]$Plan,
        [Parameter(Mandatory = $true)][string]$Path
    )

    $FullPath = Get-ProjDevFullPath -Path $Path
    foreach ($Existing in $Plan.PathPrefixes) {
        if ($FullPath.Equals(
            [string]$Existing,
            [StringComparison]::OrdinalIgnoreCase
        )) {
            return
        }
    }
    $Plan.PathPrefixes.Add($FullPath)
}

function ConvertTo-ProjDevPowerShellLiteral {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return $Value.Replace("'", "''")
}

function ConvertTo-ProjDevBatchValue {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return $Value.Replace('%', '%%')
}

function ConvertTo-ProjDevEnvironmentScripts {
    param([Parameter(Mandatory = $true)][object]$Plan)

    $GenerationPlaceholder =
        Get-ProjDevelopmentEnvironmentGenerationPlaceholder
    $Cmd = [Text.StringBuilder]::new()
    [void]$Cmd.AppendLine('@echo off')
    [void]$Cmd.AppendLine(
        'rem Generated by Swaw Kit Proj. Re-run ".dev.setup"; do not edit.'
    )
    [void]$Cmd.AppendLine(
        "set `"SWAWKIT_PROJ_DEV_GENERATION_ID=$GenerationPlaceholder`""
    )

    $Ps1 = [Text.StringBuilder]::new()
    [void]$Ps1.AppendLine(
        '# Generated by Swaw Kit Proj. Re-run ".dev.setup"; do not edit.'
    )
    [void]$Ps1.AppendLine(
        "`$env:SWAWKIT_PROJ_DEV_GENERATION_ID = " +
        "'$GenerationPlaceholder'"
    )

    foreach ($Name in $Plan.Variables.Keys) {
        $Value = $Plan.Variables[$Name]
        if ($null -eq $Value) {
            [void]$Cmd.AppendLine("set `"$Name=`"")
            [void]$Ps1.AppendLine(
                "Remove-Item -LiteralPath 'Env:$Name' -ErrorAction SilentlyContinue"
            )
            continue
        }
        $CmdValue = ConvertTo-ProjDevBatchValue -Value ([string]$Value)
        $PsValue = ConvertTo-ProjDevPowerShellLiteral -Value ([string]$Value)
        [void]$Cmd.AppendLine("set `"$Name=$CmdValue`"")
        [void]$Ps1.AppendLine("`$env:$Name = '$PsValue'")
    }

    $PathPrefix = [string]::Join(
        [IO.Path]::PathSeparator,
        [string[]]$Plan.PathPrefixes.ToArray()
    )
    if (-not [string]::IsNullOrWhiteSpace($PathPrefix)) {
        $CmdPrefix = ConvertTo-ProjDevBatchValue -Value $PathPrefix
        $PsPrefix = ConvertTo-ProjDevPowerShellLiteral -Value (
            "$PathPrefix$([IO.Path]::PathSeparator)"
        )
        [void]$Cmd.AppendLine("set `"PATH=$CmdPrefix;%PATH%`"")
        [void]$Ps1.AppendLine("`$env:PATH = '$PsPrefix' + `$env:PATH")
    }

    $UnversionedCmd = $Cmd.ToString()
    $UnversionedPs1 = $Ps1.ToString()
    $GenerationId = Get-ProjDevelopmentEnvironmentContentGenerationId `
        -CmdContent $UnversionedCmd `
        -Ps1Content $UnversionedPs1
    return [pscustomobject][ordered]@{
        GenerationId = $GenerationId
        Cmd = $UnversionedCmd.Replace(
            $GenerationPlaceholder,
            $GenerationId
        )
        Ps1 = $UnversionedPs1.Replace(
            $GenerationPlaceholder,
            $GenerationId
        )
    }
}

function Publish-ProjDevEnvironmentScripts {
    param(
        [Parameter(Mandatory = $true)][object]$Context,
        [Parameter(Mandatory = $true)][object]$Scripts
    )

    $CmdEncoding = [Text.UTF8Encoding]::new($false)
    $Ps1Encoding = [Text.UTF8Encoding]::new($true)
    $CurrentCmd = if ([IO.File]::Exists($Context.EnvCmdPath)) {
        [IO.File]::ReadAllText($Context.EnvCmdPath, $CmdEncoding)
    } else {
        $null
    }
    $CurrentPs1 = if ([IO.File]::Exists($Context.EnvPs1Path)) {
        [IO.File]::ReadAllText($Context.EnvPs1Path, $Ps1Encoding)
    } else {
        $null
    }
    if ($CurrentCmd -ceq [string]$Scripts.Cmd -and
        $CurrentPs1 -ceq [string]$Scripts.Ps1) {
        return $false
    }

    Write-ProjDevTextAtomic `
        -Path $Context.EnvCmdPath `
        -Content ([string]$Scripts.Cmd) `
        -ControlledRoot $Context.DataRoot `
        -Encoding $CmdEncoding
    Write-ProjDevTextAtomic `
        -Path $Context.EnvPs1Path `
        -Content ([string]$Scripts.Ps1) `
        -ControlledRoot $Context.DataRoot `
        -Encoding $Ps1Encoding
    return $true
}

function Publish-ProjDevEnvironmentState {
    param(
        [Parameter(Mandatory = $true)][object]$Context,
        [Parameter(Mandatory = $true)][string]$GenerationId
    )

    $State = New-ProjDevelopmentEnvironmentState `
        -GenerationId $GenerationId `
        -Declarations (Get-ProjDevelopmentDeclarationSnapshot)
    $Content = ConvertTo-ProjDevJsonText -Value $State
    $Encoding = [Text.UTF8Encoding]::new($false)
    $Current = if ([IO.File]::Exists($Context.EnvironmentStatePath)) {
        [IO.File]::ReadAllText($Context.EnvironmentStatePath, $Encoding)
    } else {
        $null
    }
    if ($Current -ceq $Content) {
        return $false
    }
    Write-ProjDevTextAtomic `
        -Path $Context.EnvironmentStatePath `
        -Content $Content `
        -ControlledRoot $Context.DataRoot `
        -Encoding $Encoding
    return $true
}
