Set-StrictMode -Version 2.0

function New-ProjDevEnvironmentPlan {
    $Variables = [Collections.Specialized.OrderedDictionary]::new()
    return [pscustomobject][ordered]@{
        Variables = $Variables
        PathPrefixes = [Collections.Generic.List[string]]::new()
    }
}

function Set-ProjDevEnvironmentVariable {
    param(
        [Parameter(Mandatory = $true)][object]$Plan,
        [Parameter(Mandatory = $true)][string]$Name,
        [AllowNull()][string]$Value
    )

    if ($Name -cnotmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "Invalid generated environment variable name: $Name"
    }
    foreach ($ExistingName in $Plan.Variables.Keys) {
        if ($Name.Equals(
            [string]$ExistingName,
            [StringComparison]::OrdinalIgnoreCase
        )) {
            throw "Generated environment variable is already defined: $Name"
        }
    }
    $Plan.Variables.Add($Name, $Value)
}

function Add-ProjDevEnvironmentPath {
    param(
        [Parameter(Mandatory = $true)][object]$Plan,
        [Parameter(Mandatory = $true)][string]$Path
    )

    $FullPath = Get-ProjDevFullPath -Path $Path
    foreach ($Existing in $Plan.PathPrefixes) {
        if ($FullPath.Equals(
            [string]$Existing,
            [StringComparison]::OrdinalIgnoreCase
        )) {
            return
        }
    }
    $Plan.PathPrefixes.Add($FullPath)
}

function ConvertTo-ProjDevPowerShellLiteral {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return $Value.Replace("'", "''")
}

function ConvertTo-ProjDevBatchValue {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return $Value.Replace('%', '%%')
}

function ConvertTo-ProjDevEnvironmentScripts {
    param(
        [Parameter(Mandatory = $true)][object]$Plan,
        [AllowEmptyString()][string]$RevisionVariable = ''
    )

    $PublishRevision = -not [string]::IsNullOrEmpty($RevisionVariable)
    $RevisionPlaceholder = $null
    if ($PublishRevision) {
        if ($RevisionVariable -cnotmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
            throw (
                'Invalid generated environment revision variable name: ' +
                $RevisionVariable
            )
        }
        foreach ($Name in $Plan.Variables.Keys) {
            if ($RevisionVariable.Equals(
                [string]$Name,
                [StringComparison]::OrdinalIgnoreCase
            )) {
                throw (
                    'Generated environment revision variable is already ' +
                    "defined: $RevisionVariable"
                )
            }
        }
        $RevisionPlaceholder =
            Get-ProjDevelopmentEnvironmentRevisionPlaceholder
    }

    $Cmd = [Text.StringBuilder]::new()
    [void]$Cmd.AppendLine('@echo off')
    [void]$Cmd.AppendLine(
        'rem Generated by Swaw Kit Proj. Regenerate it; do not edit.'
    )
    if ($PublishRevision) {
        [void]$Cmd.AppendLine(
            "set `"$RevisionVariable=$RevisionPlaceholder`""
        )
    }

    $Ps1 = [Text.StringBuilder]::new()
    [void]$Ps1.AppendLine(
        '# Generated by Swaw Kit Proj. Regenerate it; do not edit.'
    )
    if ($PublishRevision) {
        [void]$Ps1.AppendLine(
            "`$env:$RevisionVariable = '$RevisionPlaceholder'"
        )
    }
    foreach ($Name in $Plan.Variables.Keys) {
        $Value = $Plan.Variables[$Name]
        if ($null -eq $Value) {
            [void]$Cmd.AppendLine("set `"$Name=`"")
            [void]$Ps1.AppendLine(
                "Remove-Item -LiteralPath 'Env:$Name' -ErrorAction SilentlyContinue"
            )
            continue
        }
        $CmdValue = ConvertTo-ProjDevBatchValue -Value ([string]$Value)
        $PsValue = ConvertTo-ProjDevPowerShellLiteral -Value ([string]$Value)
        [void]$Cmd.AppendLine("set `"$Name=$CmdValue`"")
        [void]$Ps1.AppendLine("`$env:$Name = '$PsValue'")
    }

    $PathPrefix = [string]::Join(
        [IO.Path]::PathSeparator,
        [string[]]$Plan.PathPrefixes.ToArray()
    )
    if (-not [string]::IsNullOrWhiteSpace($PathPrefix)) {
        $CmdPrefix = ConvertTo-ProjDevBatchValue -Value $PathPrefix
        $PsPrefix = ConvertTo-ProjDevPowerShellLiteral -Value (
            "$PathPrefix$([IO.Path]::PathSeparator)"
        )
        [void]$Cmd.AppendLine("set `"PATH=$CmdPrefix;%PATH%`"")
        [void]$Ps1.AppendLine("`$env:PATH = '$PsPrefix' + `$env:PATH")
    }

    $UnversionedCmd = $Cmd.ToString()
    $UnversionedPs1 = $Ps1.ToString()
    $Revision = Get-ProjDevelopmentEnvironmentContentRevision `
        -CmdContent $UnversionedCmd `
        -Ps1Content $UnversionedPs1
    $CmdContent = $UnversionedCmd
    $Ps1Content = $UnversionedPs1
    if ($PublishRevision) {
        $CmdContent = $CmdContent.Replace(
            $RevisionPlaceholder,
            $Revision
        )
        $Ps1Content = $Ps1Content.Replace(
            $RevisionPlaceholder,
            $Revision
        )
    }
    return [pscustomobject][ordered]@{
        Revision = $Revision
        Cmd = $CmdContent
        Ps1 = $Ps1Content
    }
}

function Publish-ProjDevEnvironmentScripts {
    param(
        [Parameter(Mandatory = $true)][object]$Context,
        [Parameter(Mandatory = $true)][object]$Scripts
    )

    $CmdEncoding = [Text.UTF8Encoding]::new($false)
    $Ps1Encoding = [Text.UTF8Encoding]::new($true)
    $CurrentCmd = if ([IO.File]::Exists($Context.EnvCmdPath)) {
        [IO.File]::ReadAllText($Context.EnvCmdPath, $CmdEncoding)
    } else {
        $null
    }
    $CurrentPs1 = if ([IO.File]::Exists($Context.EnvPs1Path)) {
        [IO.File]::ReadAllText($Context.EnvPs1Path, $Ps1Encoding)
    } else {
        $null
    }
    if ($CurrentCmd -ceq [string]$Scripts.Cmd -and
        $CurrentPs1 -ceq [string]$Scripts.Ps1) {
        return $false
    }

    Write-ProjDevTextAtomic `
        -Path $Context.EnvCmdPath `
        -Content ([string]$Scripts.Cmd) `
        -ControlledRoot $Context.DataRoot `
        -Encoding $CmdEncoding
    Write-ProjDevTextAtomic `
        -Path $Context.EnvPs1Path `
        -Content ([string]$Scripts.Ps1) `
        -ControlledRoot $Context.DataRoot `
        -Encoding $Ps1Encoding
    return $true
}
